# Generated by Django 5.0 on 2025-11-27 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('concursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome', models.CharField(max_length=255, verbose_name='Nome do Cliente')),
                ('codigo_ticket', models.CharField(max_length=12, unique=True, verbose_name='Código do Ticket')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('finalizado_em', models.DateTimeField(blank=True, null=True, verbose_name='Finalizado em')),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='concursos.demanda', verbose_name='Demanda')),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['criado_em'],
                'indexes': [models.Index(fields=['demanda', 'status'], name='tickets_demanda_267f68_idx'), models.Index(fields=['codigo_ticket'], name='tickets_codigo__6db2cf_idx')],
            },
        ),
    ]
