# Generated by Django 5.0 on 2025-11-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concurso', models.CharField(max_length=255, verbose_name='Nome do Concurso')),
                ('numero_edital', models.CharField(max_length=50, verbose_name='Número do Edital')),
                ('banca', models.CharField(max_length=100, verbose_name='Banca Examinadora')),
                ('data_concurso', models.DateField(verbose_name='Data do Concurso')),
                ('cargo', models.CharField(max_length=255, verbose_name='Cargo')),
                ('autarquia', models.CharField(max_length=255, verbose_name='Órgão/Autarquia')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20, verbose_name='Status')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Demanda',
                'verbose_name_plural': 'Demandas',
                'db_table': 'demandas',
                'ordering': ['-criado_em'],
            },
        ),
    ]
